---
format: 
  pdf: 
    pdf-engine: xelatex
    keep-tex: true
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '18'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{fancyhdr}
        \usepackage{lastpage}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3em}
        \usepackage{enumitem}
        \setlist{nolistsep}
        \setlength{\columnsep}{-2.8cm}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \fancyfoot[C]{\thepage/\pageref{LastPage}}
        \AtBeginDocument{\pagestyle{fancy}}
---

<!-- TITLE -->
\begin{huge}\begin{center}{\bf SIMONE ROMITI}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}
Born: 25 Aug. 1994 | 
simone.romiti.1994@gmail.com |
\href{https://simone-romiti.github.io/}{Webpage} | 
\href{https://github.com/simone-romiti}{Github} | 
\href{https://www.linkedin.com/in/simone-romiti/}{LinkedIn} | 
\href{https://orcid.org/0000-0002-6509-447X}{Orcid} 
\end{center}
\vspace{15pt}

\hrule

\begin{large}

Theoretical physicist specialized in lattice QCD and high-performance computing, with proven expertise in Monte Carlo simulations, Machine Learning (PINNs, VAEs, diffusion models), and code optimization. 
Track record of developing innovative algorithms that achieved substantial performance improvements, and leading collaborative research projects across international institutions.
Passionate about expanding expertise and tackling complex computational challenges in collaborative, interdisciplinary environments.

\end{large}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{9pt}
  \hrule
  \vspace{9pt}

  %---------------- PhD ----------------%
  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{PhD in Theoretical Physics} (Dissertation 22 April 2022) 
    \end{flushleft}
    \begin{flushright}2018 -- 2021\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item \textbf{1st in ranking} for public admission exam to PhD program
    \item Affiliation with \href{https://www.infn.it/}{\textbf{INFN (Istituto Nazionale di Fisica Nucleare)}}{}
    \item \textbf{Tutorial sessions and teaching assistant} for undergraduate courses
  \end{itemize}

  %---------------- Master ----------------%
  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{M.S.\ in Theoretical Physics of Elementary Particles}
    \end{flushleft}
    \begin{flushright}2016 -- 2018\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item \textbf{Final grade}: 110/110 \emph{cum laude}, \textbf{GPA: 29.85/30}
  \end{itemize}

  %---------------- Bachelor ----------------%
  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{B.S.\ in Physics}
    \end{flushleft}
    \begin{flushright}2013 -- 2016\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item \textbf{Final grade}: 110/110 \emph{cum laude}, \textbf{GPA: 28.84 / 30}
    \item \textbf{Merit Scholarship} awarded for top high school marks and academic excellence.
  \end{itemize}

\end{large}

\vspace{0.05cm}



<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf WORK EXPERIENCE}
  \vspace{9pt}
  \hrule
  \vspace{9pt}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.unibe.ch/index_eng.html}{University of Bern}}\end{flushleft}
    \begin{flushright}Apr 2024--Present\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Postdoctoral Researcher}\end{flushleft}
    \begin{flushright}Bern, Switzerland\end{flushright}
  \end{multicols}
\end{large}

\vspace{-0.09cm}

\begin{large}

  \begin{itemize}
  \item \href{https://inspirehep.net/literature/3075565}{\textbf{Innovative method} using \textbf{Physics-Informed Neural Networks (PINNs)}} $\to$ exponential to polynomial scaling of memory
  \item \textbf{Reference scientist} for \href{https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=author\%3Aromiti\%20fulltext\%3AHVP&ui-citation-summary=true&ui-exclude-self-citations=true}{Hadronic Vacuum Polarization (HVP)} analysis of Bern group $\to$ sub-permille precision achievement
  \item \textbf{Pole contribution} to \href{https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=author\%3Aromiti\%20fulltext\%3AHLbL&ui-citation-summary=true&ui-exclude-self-citations=true}{Hadronic Light-by-Light contribution to $(g-2)_\mu$} $\to$ achieved $N^6$ to $N \log(N)$ scaling improvement 
  \item \href{https://github.com/simone-romiti}{\textbf{Main developer} of open-source libraries} $\to$ my code for Monte Carlo simulations led to scientific publications
  \item \textbf{Supervision of PhD students}
  \end{itemize}

\end{large}

\vspace{9pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.uni-bonn.de/en/home?set_language=en}{University of Bonn}}\end{flushleft}
    \begin{flushright}Nov 2021--Mar 2024\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Postdoctoral Researcher}\end{flushleft}
    \begin{flushright}Bonn, Germany\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.09cm}

\begin{large}

  \begin{itemize}
  \item Generated ETMC ensembles with O(a)-improved configurations, enabling more accurate lattice QCD calculations for the European Twisted Mass Collaboration
  \item \href{https://inspirehep.net/literature/2613828}{GPU code optimization} $\to$ achieved $\sim 1.5$ improvement by auto-tuning of Multigrid parameters
  \item \href{https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=author\%3Aromiti\%20title\%3ASU\%282\%29\%20OR\%20title\%3Adigitizing&ui-citation-summary=true&ui-exclude-self-citations=true}{\textbf{Novel method for SU(2) Hamiltonians}} $\to$ achieved machine-precision exactness for canonical commutation relations
  \item \href{https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=author\%3Aromiti\%20fulltext\%3Amatching&ui-citation-summary=true&ui-exclude-self-citations=true}{\textbf{Monte Carlo and Quantum Computing}} $\to$ obtained Hamiltonian limit and calculations of glueballs spectrum
  \item \textbf{Supervision of 1 Master's and 2 PhD students} of their thesis project, \textbf{tutorial sessions of undergraduate courses}
  \end{itemize}

\end{large}

\begin{large}{\bf SELECTED PUBLICATIONS}
  \vspace{9pt}
  \hrule
  \vspace{9pt}
\end{large}
\vspace{-0.15cm}

\begin{large}
  \begin{itemize}
    \item \href{https://inspirehep.net/literature/3075565}{SU(N) lattice gauge theories with Physics-Informed Neural Networks}
    \item \href{https://inspirehep.net/literature/2925594}{The anomalous magnetic moment of the muon in the Standard Model: an update}
    \item \href{https://inspirehep.net/literature/2847988}{Strange and charm quark contributions to the muon anomalous magnetic moment in lattice QCD with twisted-mass fermions}
    \item \href{https://inspirehep.net/literature/2781250}{Towards determining the (2+1)-dimensional Quantum Electrodynamics running coupling with Monte Carlo and quantum computing methods}
    \item \href{https://inspirehep.net/literature/2724218}{Digitizing lattice gauge theories in the magnetic basis: reducing the breaking of the fundamental commutation relations}
  \end{itemize}
\end{large}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{9pt}
  \hrule
  \vspace{9pt}
\end{large}
\vspace{-0.15cm}

\begin{large}

\textbf{Programming Languages} - C, C++, Python, Bash, R

\vspace{-0.15cm}
\textbf{High-Performance Computing} - openMP, MPI, CUDA, GNU/Linux, EasyBuild, SLURM

\vspace{-0.15cm}
\textbf{Frameworks and Libraries} - Jupyter, NumPy, SymPy, SciPy, Pandas, Matplotlib, Plotly, PyTorch, Streamlit

\vspace{-0.15cm}
\textbf{Computational Methods} - Monte Carlo, Bayesian statistics |  Machine Learning (PyTorch): PINNs, VAEs, diffusion models

\vspace{-0.15cm}
\textbf{Tools \& DevOps} - \LaTeX, Markdown, RMarkdown, Quarto, Docker, Git, GitHub Actions 

\vspace{-0.15cm}
\textbf{Languages} - Italian (native), English (proficient), German (A2.1)

\end{large}

\vspace{9pt}

<!-- EXTRA STUFF : 1ST BULLET -->
\begin{large}
{\bf LEADERSHIP \& RECOGNITION}
  \vspace{9pt}
  \hrule
  \vspace{9pt}
  \begin{multicols}{2}
    \begin{flushleft}    
    \textbf{Invited speaker} at \href{https://indico.ectstar.eu/event/229/}{Scale Setting workshop}
    \end{flushleft}
    \begin{flushright}
    \href{https://www.ectstar.eu/}{ECT*} | March 2025\end{flushright}
  \end{multicols}

    \vspace{-0.15cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Main organizer} of \href{https://indico.ectstar.eu/event/242/}{Hamiltonian LGTs workshop}
    \end{flushleft}
    \begin{flushright} \href{https://www.ectstar.eu/}{ECT*} | September 2025\end{flushright}
  \end{multicols}


  \vspace{-0.15cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Principal Investigator} for 240k GPU node-hours allocation
    \end{flushleft}
    \begin{flushright}\href{https://www.cscs.ch/computers/alps}{CSCS (ALPS)} | October 2025\end{flushright}
  \end{multicols}


  \vspace{-0.15cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Leading organizer} of \href{https://indico.hiskp.uni-bonn.de/category/35/}{weekly seminars at HISKP department} 
    \end{flushleft}
    \begin{flushright}\href{https://www.hiskp.uni-bonn.de/}{HISKP} | 2022 - 2024\end{flushright}
  \end{multicols}


\end{large}

