---
title: "Work Experience"
author: Simone Romiti
format: html
toc: true
toc-location: right-body
toc-expand: 3
---

# Expertise Summary

::: {.callout-warning appearance="minimal" collapse="true" title="click here to expand"}


**Computational Methods:**

- Monte Carlo algorithms and code development
- Multi-dimensional integrals (Euclidean path integral)
- Hamiltonian formulations (Kogut-Susskind)
- Tensor networks and quantum computing
- Machine Learning (PINNs, normalizing flows)
- Bayesian algorithms, Nested Sampling

**Physics Areas:**

- Precision lattice phenomenology
- Hadronic contributions to muon anomalous magnetic moment
- Transition Form Factors of pseudoscalar mesons
- Isospin breaking effects on the lattice
- Lattice Hamiltonians and solution of Schrödinger equation on truncated Hilbert spaces

**Technical Skills:**

- High-performance computing (HPC): CPU and GPU parallel computing, Data Structures and Algorithms
- Open-source software development: `git` version control, CI/Cd, DevOps
- Collaboration leadership and project management
- Cross-disciplinary research integration

:::



# Work positions


::: {.callout-note appearance="minimal" collapse="true"}
## Postdoctoral Researcher (April 2024 - present) | Bern -- click here to expand

*April 2024 – present* · [**University of Bern**, Switzerland](https://www.unibe.ch/)

**Department:**  
[Institute for Theoretical Physics, Albert Einstein Center for Fundamental Physics (AEC)](https://www.itp.unibe.ch/)

**Key Activities:**

- **Machine Learning applications:**  
  - Independently developed Physics-Informed Neural Networks (PINNs) method for solving eigenvalue problems in $\mathrm{SU}(N)$ lattice Hamiltonians | overcoming Hilbert space truncation exponential scaling

- **Hadronic contributions to muon $(g-2)_\mu$:**  
  - Leading contributor to Hadronic Vacuum Polarization (HVP) calculations for $u,d,s,c$ flavors and Leading Isospin Breaking corrections. **Reference person** for Bern group in ETM collaboration's blinded HVP analysis.
  - Implementation and calculation of meson pole contributions to Hadronic Light-by-Light (HLbL) scattering. 
    Represented collaboration at 2025 $(g-2)_\mu$ Initiative workshop
    Included in author list of 2025 $(g-2)_\mu$ Whitepaper

- **Transition Form Factors (TFFs):**  
  - Principal Investigator for [CSCS](https://www.cscs.ch/) computing time allocation of 240k GPU node hours, for the calculation of $P\to\gamma^*\gamma^*$ transition form factors for $\eta,\eta'$ mesons: continuum limit over the ETM ensembles.

- **Numerical developments:**  
  - Developed open-source implementation of pseudoscalar meson pole contributions (infinite and finite volume)
  - Advanced work on precision lattice QCD at sub-permille level
  - Nested sampling algorithm for lattice field theories

- **Supervision of PhD** students

- **Invited speaker** at 2025 [Scale Setting Workshop (ECT*)](https://indico.ectstar.eu/event/229/)
- **Main organizer** of [Hamiltonian lattice gauge theories workshop (ECT*)](https://indico.ectstar.eu/event/242/)
- **Organization support** for [SIGN25 workshop at ITP Bern](http://sign25.itp.unibe.ch/index.html)


:::

::: {.callout-note appearance="minimal" collapse="true"}

## Postdoctoral Researcher (Nov. 2021 - Mar. 2024) | Bonn -- click here to expand


*Nov 2021 – Mar. 2024* · **University of Bonn**, Germany  

**Department:**  
[Helmholtz Institute for Radiation and Nuclear Physics (HISKP)](https://www.hiskp.uni-bonn.de/)

**Key Activities:**

- **Ensemble production and analysis:**  
  - Contributed to generation and analysis of Extended Twisted Mass Collaboration (ETMC) gauge configurations
  - Code development for `tmLQCD` library

- **Hamiltonian formulations:**  
  - Quantum computing simulations of $\mathrm{U}(1)$ gauge theories in 2+1 dimensions
  - Main developer and maintainer of specialized Monte Carlo library for Hamiltonian lattice gauge theories
  - Developed novel algorithms for $\mathrm{SU}(2)$ gauge theories maximizing canonical commutation relations
  - Work on Hilbert space truncations via group manifold partitioning

- **Supervision of MS and PhD students**


- **Teaching:**  
  - Tutorial sessions for undergraduate courses (see [teaching section](teaching.qmd))

- **Organization support for the [Lattice 2022 international conference](https://indico.hiskp.uni-bonn.de/event/40/)  

:::

::: {.callout-note appearance="minimal" collapse="true"}

## Ph.D. Student (Nov. 2018 - Oct. 2021) | Rome -- click here to expand


*Nov 2018 – Oct 2021* · **Roma Tre University**, Rome, Italy  

**Department:**  
[Department of Mathematics and Physics](https://matematicafisica.uniroma3.it/)

**Research Focus:**

- **Leading Isospin Breaking Effects (LIBEs):**  
  - Calculated LIBEs on nucleon spectrum and $\Delta(1232)$ resonances using RM123 method
  - Provided one of few lattice calculations of neutron-proton mass difference
  - Determined $\Delta(1232)$ mass splittings

- **Methodological development:**  
  - Spectral decomposition of Euclidean lattice correlators
  - Advanced understanding of isospin symmetry breaking in QCD

- **Teaching:**  
  - Tutorial sessions for undergraduate courses

**Outcomes:**: Successfully defended Ph.D. thesis | Submission: 31st Oct. 2021 | Dissertation: 22 Apr. 2022

:::

# Awards and grants

::: {.callout-tip appearance="minimal" collapse="true" title="click here to expand"}

- **2025-2026**: **Principal Investigator (PI)** of computing time allocation: $0.24 \cdot 10^{6}$ GPU node hours on [ALPS - CSCS](https://www.cscs.ch/computers/alps) Swiss supercomputing cluster | Lattice calculation of the $\eta,\eta'$ Transition form factors.


- **2013-2016**: Merit Scholarship for excellent students - Physics Department, Roma Tre University. Awarded for
top high school marks and academic excellence.

:::