---
format: 
  pdf: 
    pdf-engine: xelatex
    keep-tex: true
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '18'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{fancyhdr}
        \usepackage{lastpage}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3em}
        \usepackage{enumitem}
        \setlist{nolistsep}
        \setlength{\columnsep}{-2.8cm}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \fancyfoot[C]{\thepage/\pageref{LastPage}}
        \AtBeginDocument{\pagestyle{fancy}}
---

<!-- TITLE -->
\begin{huge}\begin{center}{\bf SIMONE ROMITI}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}
\href{mailto:simone.romiti.1994@gmail.com}{simone.romiti.1994@gmail.com} |
\href{https://simone-romiti.github.io/}{Website} | 
\href{https://github.com/simone-romiti}{GitHub} | 
\href{https://www.linkedin.com/in/simone-romiti/}{LinkedIn} |
\href{https://orcid.org/0000-0002-6509-447X}{ORCID}
\end{center}
\vspace{15pt}

\hrule

\begin{large}

```{python}
#| echo: false
#| output: asis

from datetime import date
years = (date.today() - date(2022, 4, 22)).days // 365

print(f"""

I am a theoretical physicist specialized in lattice gauge theories, with {years}+ years of postdoctoral experience.
My research focuses on phenomenological predictions for lattice QCD, and algorithms development for the simulation of strongly-interacting quantum field theories on the lattice.
My computational expertise includes high-performance computing for large-scale numerical simulations, Bayesian methods, and machine learning techniques for many-body systems (Physics-Informed Neural Networks, Diffusion Models).
I have a proven track record of designing algorithms that delivered order-of-magnitude performance gains, of building open-source scientific software used in peer-reviewed research, and leading collaborative projects across international research institutions.

""")

```


\end{large}

\vspace{9pt}

<!-- SKILLS -->
\begin{large}{\bf TECHNICAL SKILLS}
  \vspace{9pt}
  \hrule
  \vspace{9pt}
\end{large}
\vspace{-0.15cm}

\begin{large}

\textbf{Programming Languages} - C, C++, Python, Bash, R, SQL

\vspace{-0.15cm}
\textbf{HPC \& Systems} - CUDA, MPI, OpenMP, SLURM, EasyBuild, GNU/Linux

\vspace{-0.15cm}
\textbf{ML \& Data} - PINNs, VAEs, Diffusion Models, Bayesian Statistics, Markov Chain Monte Carlo, Nested Sampling

\vspace{-0.15cm}
\textbf{Libraries \& Frameworks} - PyTorch, NumPy, SciPy, Pandas, Matplotlib, Plotly, Streamlit, SymPy, Jupyter

\vspace{-0.15cm}
\textbf{DevOps \& Tools} - Git, GitHub Actions, CI/CD, Docker, \LaTeX, Quarto, Markdown

\vspace{-0.15cm}
\textbf{Spoken Languages} - Italian (native), English (fluent), German (basic)

\end{large}

\vspace{9pt}

<!-- EXPERIENCE -->
\begin{large}{\bf WORK EXPERIENCE}
  \vspace{9pt}
  \hrule
  \vspace{9pt}

  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.unibe.ch/index_eng.html}{University of Bern}}\end{flushleft}
    \begin{flushright}Apr 2024 -- Present\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Postdoctoral Research Scientist}\end{flushleft}
    \begin{flushright}Bern, Switzerland\end{flushright}
  \end{multicols}
\end{large}

\vspace{-0.09cm}

\begin{large}
  \begin{itemize}
    \item \textbf{Designed novel algorithm for the solution of lattice Hamiltonians} using Physics-Informed Neural Networks (PINNs)
    \item \textbf{Achieved sub-permille numerical precision} as lead developer for a high-accuracy scientific computation of HVP contribution to the muon's ${g_\mu-2}$
    \item \textbf{Improved algorithm scaling from $O(N^6)$ to $O(N \log N)$} through a novel mathematical reformulation using FFTs and convolutions, entering in the HLbL contribution to ${g_\mu-2}$
    \item \textbf{Built and maintained open-source simulation libraries} (Python/C++) adopted across multiple research groups and directly enabling peer-reviewed publications
    \item \textbf{Mentored 3 PhD students} on software engineering practices, numerical methods, and project delivery
  \end{itemize}
\end{large}

\vspace{9pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.uni-bonn.de/en/home?set_language=en}{University of Bonn}}\end{flushleft}
    \begin{flushright}Nov 2021 -- Mar 2024\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Postdoctoral Research Scientist}\end{flushleft}
    \begin{flushright}Bonn, Germany\end{flushright}
  \end{multicols}
\end{large}

\vspace{-0.09cm}

\begin{large}
  \begin{itemize}
    \item \textbf{Optimized GPU kernels (CUDA)}, achieving a $\sim$1.5$\times$ throughput improvement via auto-tuning of Multigrid solver parameters on HPC clusters
    \item \textbf{Designed and ran large-scale distributed simulations} (MPI/OpenMP) on international computing centers
    \item \textbf{Developed a novel numerical formulation of canonical momenta in $SU(N)$}, achieving machine-precision exactness for a class of operator algebra constraints
    \item \textbf{Integrated Monte Carlo simulations with quantum computing workflows}, delivering end-to-end prototype pipelines bridging classical HPC and quantum backends
    \item \textbf{Mentored 3 graduate students} and delivered tutorial sessions for undergraduate computing courses
  \end{itemize}
\end{large}

\vspace{9pt}

<!-- PUBLICATIONS -->
\begin{large}{\bf SELECTED PUBLICATIONS}
  \vspace{9pt}
  \hrule
  \vspace{9pt}

   \begin{itemize}
     \item \href{https://inspirehep.net/literature/3075565}{SU(N) lattice gauge theories with Physics-Informed Neural Networks}
     \item \href{https://inspirehep.net/literature/2925594}{The anomalous magnetic moment of the muon in the Standard Model: an update}
     \item \href{https://inspirehep.net/literature/2847988}{Strange and charm quark contributions to the muon anomalous magnetic moment in lattice QCD with twisted-mass fermions}
     \item \href{https://inspirehep.net/literature/2781250}{Towards determining the (2+1)-dimensional Quantum Electrodynamics running coupling with Monte Carlo and quantum computing methods}
     \item \href{https://inspirehep.net/literature/2724218}{Digitizing lattice gauge theories in the magnetic basis: reducing the breaking of the fundamental commutation relations}
   \end{itemize}

\end{large}

\vspace{9pt}

<!-- EDUCATION -->
\begin{large}{\bf EDUCATION}
  \vspace{9pt}
  \hrule
  \vspace{9pt}

  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{PhD in Physics} (Dissertation April 2022) 
    \end{flushleft}
    \begin{flushright}Nov. 2018 -- Oct. 2021\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item Thesis: \textit{Non-perturbative aspects of gauge theories on the lattice: algorithms, simulations and quantum computing}
    \item Focus: Monte Carlo methods, HPC simulations, Isospin Breaking effects in lattice QCD
    \item Ranked \textbf{1st} in national competitive admission exam
  \end{itemize}

  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{M.S.\ in Physics}
    \end{flushleft}
    \begin{flushright}Oct. 2016 -- Oct. 2018\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item GPA: 29.85/30, graduated with highest honours
  \end{itemize}

  \begin{multicols}{2}
    \begin{flushleft}{\href{https://www.uniroma3.it/}{\textit{Roma Tre University}}}\end{flushleft}
    \begin{flushright}Rome, Italy\end{flushright}
  \end{multicols}
  \vspace{-0.15cm}
  \begin{multicols}{2}
    \begin{flushleft}
    \textbf{B.S.\ in Physics}
    \end{flushleft}
    \begin{flushright}Oct. 2013 -- Jul. 2016\end{flushright}
  \end{multicols}
  \vspace{-0.2cm}
  \begin{itemize}
    \item GPA: 28.84/30, graduated with highest honours | Merit Scholarship recipient
  \end{itemize}

\end{large}

\vspace{9pt}

<!-- LEADERSHIP -->
\begin{large}
{\bf LEADERSHIP \& ACHIEVEMENTS}
  \vspace{9pt}
  \hrule
  \vspace{9pt}

\setlength{\columnsep}{-4.5cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Principal Investigator} of computing time allocation grants, one at \href{https://www.cscs.ch/computers/alps}{CSCS ALPS} and one at \href{https://www.gauss-centre.eu/}{GCS}
    \end{flushleft}
    \begin{flushright} | 2025\end{flushright}
  \end{multicols}

  \vspace{-0.15cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Workshop Organizer} -- HPC \& Quantum Computing workshop
    \end{flushleft}
    \begin{flushright}\href{https://indico.ectstar.eu/event/242/}{ECT*} | 2025\end{flushright}
  \end{multicols}

  \vspace{-0.15cm}

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Invited Speaker} -- Scientific seminars at \href{https://indico.cern.ch/category/376/}{CERN} and \href{https://indico.ectstar.eu/event/229/contributions/5308/}{ECT*}
    \end{flushleft}
    \begin{flushright}2025 -- 2026\end{flushright}
  \end{multicols}

  \vspace{-0.15cm}  

  \begin{multicols}{2}
    \begin{flushleft}    
      \textbf{Visiting Research Grant} -- \href{https://www.philnat.unibe.ch/e17097/e95924/e1163513/e1163533/OpenRound2026_01_2_eng.pdf}{Open round 2026/1 fund}
    \end{flushleft}
    \begin{flushright}\href{https://www.tuwien.at/}{TU Wien} | 2026\end{flushright}
  \end{multicols}


\end{large}
